# inventory/group_vars/netbox/example_secrets.yml
# Скопируй в inventory/group_vars/netbox/secrets.yml
# и заполни своими значениями

# VRRP / Keepalived
vrrp_auth_pass: "CHANGE_ME"

# PostgreSQL / Patroni
pg_superuser_password: "CHANGE_ME"
replication_password: "CHANGE_ME"

# Redis
redis_password: "CHANGE_ME"

# PgBouncer (если используешь)
pgb_admin_pass: "CHANGE_ME"
pgb_stats_pass: "CHANGE_ME"

# Netbox
netbox_peppers: "CHANGE_ME"  # openssl rand -hex 32
netbox_secret_key: "CHANGE_ME"
netbox_superuser:
  username: "admin"  # CHANGE_ME
  email: "admin@admin.admin"  # CHANGE_ME
  password: "admin"  # CHANGE_ME

# check file ldap_config.py.j2
ldap_backend:
  active: false  # or 'true'
  uri: "CHANGE_ME"
  password: "CHANGE_ME"

# (опционально) любые токены/ключи/пароли, которые не должны попадать в git
