angie_work_path: "/etc/angie/"
angie_main_conf: "/etc/angie/angie.conf"
angie_prometheus_all: "/etc/angie/prometheus_all.conf"
angie_fastcgi_conf: "/etc/angie/fastcgi.conf"
angie_mime_types: "/etc/angie/mime.types"
angie_http_path: "/etc/angie/http.d"
angie_http_conf: "/etc/angie/http.d/default.conf"
angie_stream_path: "/etc/angie/stream.d"
angie_stream_conf: "/etc/angie/stream.d/example.conf"
angie_conf_path: "/etc/angie/conf.d"
angie_modules_path: "/etc/angie/modules"
angie_fastcgi_params_path: "/etc/angie/fastcgi_params"
angie_scgi_params_path: "/etc/angie/scgi_params"
angie_uwsgi_params_path: "/etc/angie/uwsgi_params"
